config/routes.rb
Rails.application.routes.draw do
  post 'result', to: "euclid#result"
  root "euclid#index"
  get 'euclid/xml_dump'
end

app/models/euclid_result.rb
# frozen_string_literal: true

# results of euclid algorithm
class EuclidResult < ApplicationRecord
  validates :first, uniqueness: { scope: :second }
  validates :first, :second, :gcd, :lcm, presence: true
  validate :unique_pair, on: :create

  has_many :euclid_steps

  def self.get(first, second)
    result = find_by(first:, second:)
    result = find_by(first:, second:) if result.blank?
    return [result.euclid_steps.all.order(:step), result.gcd, result.lcm] unless result.blank?

    generate_result(first, second)
  end

  def self.get_json(first, second)
    response_to_json(*get(first, second))
  end

  def to_xml
    Nokogiri::XML::Builder.new do |xml|
      xml.result do
        xml.id id
        xml.gcd gcd
        xml.lcm lcm
        xml.steps do
          euclid_steps.all.each do |step|
            xml.step do
              xml.id step.id
              xml.first step.first
              xml.second step.second
            end
          end
        end
      end
    end.doc.root.to_xml
  end

  private

  def unique_pair
    errors.add(:already_calculated, 'results for such numbers') unless
      EuclidResult.find_by(first: second, second: first).nil?
  end

  def self.generate_result(first, second)
    steps, gcd, lcm = euclid_algorithm(first, second)

    res = create(first:, second:, gcd:, lcm:)

    step_objects = steps.reduce([]) do |sum, step|
      step_res, index = step
      sum.push(EuclidStep.create(euclid_result_id: res.id, step: index,
                                 first: step_res[0], second: step_res[1]))
    end

    [step_objects, gcd, lcm]
  end

  def self.euclid_algorithm(first, second)
    results = euclid_enumerator(first, second)
              .each_with_index
              .take_while { |res, _| [res[0], res[1]].min != 0 }

    gcd = results.blank? ? first : results[-1][0].max
    lcm = first * second / gcd

    [results, gcd, lcm]
  end

  def self.euclid_enumerator(first, second)
    Enumerator.new do |yielder|
      loop do
        yielder << if first < second
                     [first, second -= first]
                   else
                     [first -= second, second]
                   end
      end
    end
  end

  def self.response_to_json(res_steps, gcd, lcm)
    ActiveSupport::JSON.encode(
      { steps: res_steps,
        gcd:,
        lcm: }
    )
  end

  private_class_method :generate_result, :euclid_enumerator,
                       :euclid_algorithm, :response_to_json
end

app/models/euclid_step.rb
# frozen_string_literal: true

# steps of euclid algorithm
class EuclidStep < ApplicationRecord
  belongs_to :euclid_result
  validates :step, uniqueness: { scope: :euclid_result_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true
end

app/controllers/euclid_controller.rb
# frozen_string_literal: true

# main controller
class EuclidController < ApplicationController
  before_action :validate_input, only: :result
  before_action :require_login

  def index; end

  def result
    @first_num = params[:input1].to_i
    @second_num = params[:input2].to_i

    @results, @gcd, @lcm = euclid_algorithm
  end

  private

  def euclid_algorithm
    results = euclid_enumerator(@first_num, @second_num)
              .each_with_index
              .take_while { |res, _| [res[0], res[1]].min != 0 }

    gcd = results.blank? ? @first_num : results[-1][0].max
    lcm = @first_num * @second_num / gcd

    [results, gcd, lcm]
  end

  def euclid_enumerator(first, second)
    Enumerator.new do |yielder|
      loop do
        yielder << if first < second
                     [first, second -= first]
                   else
                     [first -= second, second]
                   end
      end
    end
  end

  def validate_input
    unless valid(params[:input1]) && valid(params[:input2])
      redirect_to input_path, alert: 'You should enter a natural number in each field'
    end
  end

  def valid(input)
    return false if input.to_i.zero?

    /\A\d+\Z/.match?(input)
  end

  def require_login
    redirect_to root_path if session[:current_user_id].nil?
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

# session controller
class SessionController < ApplicationController
  def login; end

  def authorize
    user = User.find_by_username(params[:username])
    return redirect_to_login unless user&.authenticate params[:password]

    session[:current_user_id] = user.id
    redirect_to input_path
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path
  end

  private

  def redirect_to_login
    redirect_to root_path, flash: { alert: 'Wrong login or password' }
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# scaffold-generated controller for users
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/euclid/_result.html.erb
<div id="result">
  <table class="table">
    <tr>
      <th>Iteration</th>
      <th>First number</th>
      <th>Second number</th>
    </tr>

    <tr>
      <th>Initial</th>
      <th><%= @first_num %></th>
      <th><%= @second_num %></th>
    </tr>

    <% @results.each do |res, index| %>
      <tr>
        <td><%= index %></td>
        <td><%= res[0] %></td>
        <td><%= res[1] %></td>
      </tr>
    <% end %>

    <tr>
      <th>Operation</th>
      <th>Greatest common denominator</th>
      <th>Least common Multiple</th>
    </tr>

    <tr>
      <th>Result</th>
      <th id="gcd"><%= @gcd %></th>
      <th id="lcm"><%= @lcm %></th>
    </tr>
  </table>
</div>

app/views/euclid/index.html.erb
<% flash.each do |_type, msg| %>
  <p class="text-danger mt-2"><%= msg %></p>
<% end %>

<div class="col-8 m-auto">
  <%= form_with url: result_path, id: "form" do |form| %>
    <div class="form-group row my-3">
      <%=  form.label :input1, "Value 1:", class: "col-md-2 col-lg-1 col-form-label"  %>
      <div class="col-md-10 col-lg-6">
        <%=  form.number_field :input1, class: "form-control", value: "35" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%=  form.label :input2, "Value 2:", class: "col-md-2 col-lg-1 col-form-label"  %>
      <div class="col-md-10 col-lg-6">
        <%=  form.number_field :input2, min: 1, class: "form-control", value: "45" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <div class="col-md-2 col-lg-1"></div>
      <div class="col-md-7 col-lg-5">
        <%=  form.submit "Calculate greatest common denominator", class: 'btn btn-outline-primary' %>
      </div>
    </div>
  <% end %>

  <div id="result"></div>
</div>

app/views/euclid/result.html.erb
<div class="col-md-8 col-lg-4 m-auto">
  <table class="table">
    <tr>
      <th>Step</th>
      <th>lhs</th>
      <th>rhs</th>
    </tr>

    <tr>
      <td>Initial</td>
      <td><%= @first_num %></td>
      <td><%= @second_num  %></td>
    </tr>

    <% @results.each do |res, ind| %>
      <tr>
        <td><%= ind %></td>
        <td><%= res[0] %></td>
        <td><%= res[1]  %></td>
      </tr>
    <% end %>

    <tr>
      <th> Operation </th>
      <th>Greatest common denominator</th>
      <th>Least common multiple</th>
    </tr>

    <tr>
      <th>Result</th>
      <td><%= @gcd %></td>
      <td><%= @lcm %></td>
    </tr>
  </table>
  <h4><%= link_to "Go back", "/", class: "link" %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Labs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "bootstrap.min" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <div class="row bg-primary">
      <h1 class="col-6 mt-3 text-light">Euclid's Algorithm</h1>
      <% unless session[:current_user_id].nil? %>
        <div class="col-4"></div>
        <div class="col-2 d-flex align-items-center justify-content-center">
          <a href="<%= logout_path %>" class="text-light h4">Sign Out</a>
        </div>
      <% end %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/login.html.erb
<% flash.each do |type, msg| %>
  <% unless type == "notice" %>
    <p class="text-danger mt-2"><%= msg %></p>
  <% end %>
<% end %>

<%= form_with url: authorize_path, local: true  do |form| %>
  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div class="mt-2 d-flex align-items-center">
    <%= form.submit class: "btn btn-primary", value: 'Login' %>
    <a href="<%= new_user_path %>" class="ms-1 link text-primary">Sign Up</a>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
<!--      <h2><%#= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>-->

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>