xml-proxy/config/routes.rb
Rails.application.routes.draw do
  get 'output', to: "proxy#output"
  root "proxy#input"
end

xml-proxy/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

xml-proxy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

xml-proxy/app/controllers/proxy_controller.rb
# frozen_string_literal: true

require 'open-uri'

# Controller receiving xml from api and converting it to html
class ProxyController < ApplicationController
  before_action :parse_params, only: :output

  def input; end

  def output
    # rubocop:disable Security/Open
    xml_response = URI.open(url)
    # rubocop:enable Security/Open

    case @side
    when 'client'
      render xml: add_xslt_ref(xml_response).to_xml
    when 'server'
      @result = xslt_transform(xml_response).to_html
    else
      render xml: xml_response
    end
  end

  private

  def parse_params
    @first = params[:input1]
    @second = params[:input2]
    @side = params[:side]
  end

  def url
    "http://127.0.0.1:3000/?input1=#{@first}&input2=#{@second}"
  end

  def xslt_transform(data)
    doc = Nokogiri::XML(data)
    xslt = Nokogiri::XSLT(File.read("#{Rails.root}/public/transform.xslt"))
    xslt.transform(doc)
  end

  def add_xslt_ref(data)
    doc = Nokogiri::XML(data)
    xslt = Nokogiri::XML::ProcessingInstruction.new(doc, 'xml-stylesheet',
                                                    'type="text/xsl" href="/browser.xslt"')
    doc.root.add_previous_sibling(xslt)
    doc
  end
end

xml-proxy/app/helpers/application_helper.rb
module ApplicationHelper
end

xml-proxy/app/helpers/proxy_helper.rb
module ProxyHelper
end

xml-proxy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-turbo='false'>
  <head>
    <title>Rails Labs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "bootstrap.min" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <div class="row bg-primary">
      <h1 class="col-6 mt-3 text-light">Euclid's Algorithm</h1>
    </div>
    <div class="row">
      <%= yield %>
    </div>
  </body>
</html>

xml-proxy/app/views/proxy/input.html.erb
<% flash.each do |_type, msg| %>
  <p class="text-danger mt-2"><%= msg %></p>
<% end %>

<div class="col-8 m-auto">
  <%= form_with url: output_path, method: 'get', id: "form" do |form| %>
    <div class="form-group row my-3">
      <%= form.label :input1, "Value 1:", class: "col-md-2 col-lg-1 col-form-label"  %>
      <div class="col-md-10 col-lg-6">
        <%= form.number_field :input1, class: "form-control", value: "35" %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :input2, "Value 2:", class: "col-md-2 col-lg-1 col-form-label"  %>
      <div class="col-md-10 col-lg-6">
        <%= form.number_field :input2, min: 1, class: "form-control", value: "45" %>
      </div>
    </div>

    <div class="form-check">
      <%= form.label :side_server, "Трансформация на стороне сервера", class: "form-check-label" %>
      <%= form.radio_button :side, 'server', class: "form-check-input"%>
    </div>

    <div class="form-check">
      <%= form.label :side_client, "Трансформация на стороне браузера", class: "form-check-label" %>
      <%= form.radio_button :side, 'client', class: "form-check-input" %>
    </div>

    <div class="form-group row mt-3">
      <div class="col-md-7 col-lg-5">
        <%= form.submit "Calculate greatest common denominator", class: 'btn btn-outline-primary' %>
      </div>
    </div>
  <% end %>
</div>

xml-proxy/app/views/proxy/output.html.erb
<%= render inline: @result  %>
<a href="<%= root_path %>" class="link-primary"> Go back </a>